### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by WRZack** [jzfai/vue3-admin-plus#20]
> vue3-admin-plus@1.3.3 dev D:\dev\NKFABack
> vite --mode serve-dev --host

fatal: Needed a single revision
failed to load config from D:\dev\NKFABack\vite.config.js
error when starting dev server:
Error: Command failed: git rev-parse --short HEAD
fatal: Needed a single revision

    at checkExecSyncError (child_process.js:790:11)
    at Object.execSync (child_process.js:863:15)
    at Object.<anonymous> (D:\dev\NKFABack\vite.config.js:65:32)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.require.extensions.<computed> [as .js] (D:\dev\NKFABack\node_modules\.pnpm\vite@2.7.3_sass@1.32.12\node_modules\vite\dist\node\chunks\dep-5496817b.js:82494:20)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at loadConfigFromBundledFile (D:\dev\NKFABack\node_modules\.pnpm\vite@2.7.3_sass@1.32.12\node_modules\vite\dist\node\chunks\dep-5496817b.js:82502:17)
    at loadConfigFromFile (D:\dev\NKFABack\node_modules\.pnpm\vite@2.7.3_sass@1.32.12\node_modules\vite\dist\node\chunks\dep-5496817b.js:82421:32)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async resolveConfig (D:\dev\NKFABack\node_modules\.pnpm\vite@2.7.3_sass@1.32.12\node_modules\vite\dist\node\chunks\dep-5496817b.js:81991:28)
    at async createServer (D:\dev\NKFABack\node_modules\.pnpm\vite@2.7.3_sass@1.32.12\node_modules\vite\dist\node\chunks\dep-5496817b.js:67664:20)
    at async CAC.<anonymous> (D:\dev\NKFABack\node_modules\.pnpm\vite@2.7.3_sass@1.32.12\node_modules\vite\dist\node\cli.js:688:24)
 ELIFECYCLE  Command failed with exit code 1.

Process finished with exit code 1
请问这是什么引起的

**Comment by jzfai** [comment]
sorry ,  i need you run
 npx envinfo --system --npmPackages '{vite,@vitejs/*}' --binaries --browsers 
 to console the system info
 
我需要你运行下这个命名
npm i -g npx
npx envinfo --system --npmPackages '{vite,@vitejs/*}' --binaries --browsers 
输出下您的系统信息来排查问题
